# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(default='USD', max_length=3)),
                ('short_name', models.CharField(default='$', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bids_count', models.IntegerField(default=0)),
                ('average_bid', models.IntegerField(default=0)),
                ('min_payment', models.IntegerField(default=0)),
                ('max_payment', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('bidders', models.ManyToManyField(related_name='bidders_related', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAdditionalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=orders.models.get_project_file_path)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='---')),
                ('image', models.ImageField(upload_to='images/tech_images/')),
                ('mini_image', models.ImageField(upload_to='images/tech_images/mini/')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='required_technologies',
            field=models.ManyToManyField(to='orders.Technology'),
        ),
    ]
